package io.github.loredock.agent.model.enums;

/** Agent 运行失败或终止的稳定错误码，不保存底层异常原文。 */
public enum AgentErrorCode {
    AGENT_RUN_IDEMPOTENCY_CONFLICT,
    AGENT_SKILL_UNAVAILABLE,
    AGENT_DISABLED,
    AGENT_RUNTIME_UNAVAILABLE,
    AGENT_RUNTIME_BUSY,
    AGENT_MODEL_UNAVAILABLE,
    AGENT_MODEL_RESPONSE_INVALID,
    AGENT_TOOL_NOT_ALLOWED,
    AGENT_TOOL_SCOPE_VIOLATION,
    AGENT_EVIDENCE_VERSION_CHANGED,
    AGENT_STEP_LIMIT_EXCEEDED,
    AGENT_MODEL_CALL_LIMIT_EXCEEDED,
    AGENT_RUN_TIMEOUT,
    AGENT_RUN_INTERRUPTED,
    /** 管理员主动停止知识整理运行（AgentRunMapper.cancelKnowledge 写入）。 */
    AGENT_RUN_CANCELLED,
    /** 恢复或续跑时发现 run 定义摘要或 Graph 定义版本与当前不一致，停止解析旧 Checkpoint。 */
    AGENT_DEFINITION_MISMATCH,
    AGENT_CITATION_INVALID,
    AGENT_INTERNAL_ERROR
}
