-- user-memory（记忆管理）：用户长期偏好（格式/模板/内容/风格/流程）跨会话沉淀。
-- 语义约束：共享（无用户隔离）；只区分 GLOBAL/PROJECT 两级范围；不设唯一键——
-- 语义去重由写入判断层负责，且「冲突双写」必须允许两条并存。
CREATE TABLE user_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(16) NOT NULL,
    project_id BIGINT,
    project_identifier VARCHAR(64),
    category VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(300) NOT NULL,
    content VARCHAR(4000) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_run_id BIGINT,
    source_conversation_id BIGINT,
    status VARCHAR(16) NOT NULL,
    use_count BIGINT NOT NULL DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_user_memory_project
        FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT fk_user_memory_source_run
        FOREIGN KEY (source_run_id) REFERENCES agent_run(id),
    CONSTRAINT fk_user_memory_source_conversation
        FOREIGN KEY (source_conversation_id) REFERENCES knowledge_task_conversation(id),
    CONSTRAINT ck_user_memory_scope CHECK (
        (scope_type = 'GLOBAL' AND project_id IS NULL AND project_identifier IS NULL)
        OR (scope_type = 'PROJECT' AND project_id IS NOT NULL AND project_identifier IS NOT NULL)
    ),
    CONSTRAINT ck_user_memory_category CHECK (
        category IN ('FORMAT', 'TEMPLATE', 'CONTENT', 'STYLE', 'PROCESS', 'OTHER')
    ),
    CONSTRAINT ck_user_memory_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_user_memory_source_type CHECK (
        source_type IN ('KNOWLEDGE_CURATION', 'MANUAL')
    ),
    CONSTRAINT ck_user_memory_source_pair CHECK (
        (source_type = 'KNOWLEDGE_CURATION'
            AND source_run_id IS NOT NULL AND source_conversation_id IS NOT NULL)
        OR (source_type = 'MANUAL'
            AND source_run_id IS NULL AND source_conversation_id IS NULL)
    ),
    CONSTRAINT ck_user_memory_text CHECK (
        length(scope_type) BETWEEN 1 AND 16
        AND (
            (scope_type = 'GLOBAL' AND project_identifier IS NULL)
            OR (scope_type = 'PROJECT' AND length(project_identifier) BETWEEN 1 AND 64)
        )
        AND length(category) BETWEEN 1 AND 32
        AND length(title) BETWEEN 1 AND 200
        AND length(summary) BETWEEN 1 AND 300
        AND length(content) BETWEEN 1 AND 4000
        AND length(created_by) BETWEEN 1 AND 128
        AND length(updated_by) BETWEEN 1 AND 128
    ),
    CONSTRAINT ck_user_memory_use_count CHECK (use_count >= 0),
    CONSTRAINT ck_user_memory_used_at CHECK (
        last_used_at IS NULL
        OR last_used_at >= created_at
    ),
    CONSTRAINT ck_user_memory_time CHECK (updated_at >= created_at)
);

CREATE INDEX idx_user_memory_scope_status
    ON user_memory(scope_type, project_id, status, updated_at DESC, id DESC);

COMMENT ON TABLE user_memory IS '用户长期偏好记忆；共享语义不按用户隔离，仅供主 Agent 作为偏好上下文，不作为知识事实或证据引用';
COMMENT ON COLUMN user_memory.scope_type IS 'GLOBAL 通用或 PROJECT 项目；记忆的项目范围一经创建不可编辑';
COMMENT ON COLUMN user_memory.project_id IS 'PROJECT 范围必填且必须指向启用中的项目；GLOBAL 范围必须为空';
COMMENT ON COLUMN user_memory.project_identifier IS '所属项目的稳定业务标识，冗余存储用于检索过滤展示';
COMMENT ON COLUMN user_memory.category IS '记忆分类：FORMAT/TEMPLATE/CONTENT/STYLE/PROCESS/OTHER';
COMMENT ON COLUMN user_memory.title IS '短标题，用于摘要行展示（≤200 字符）；标题命中权重高于正文';
COMMENT ON COLUMN user_memory.summary IS '注入摘要（≤300 字符），注入剪裁时不得超长';
COMMENT ON COLUMN user_memory.content IS '记忆正文（≤4000 字符），按需经 memory_read 加载';
COMMENT ON COLUMN user_memory.source_type IS 'KNOWLEDGE_CURATION 由知识整理会话提炼，MANUAL 由管理员创建';
COMMENT ON COLUMN user_memory.source_run_id IS '提炼来源 run；KNOWLEDGE_CURATION 必填且用于写入预算（单 run 累计上限）';
COMMENT ON COLUMN user_memory.source_conversation_id IS '提炼来源会话；KNOWLEDGE_CURATION 必填';
COMMENT ON COLUMN user_memory.status IS 'ACTIVE 可检索可加载，DISABLED 人工停用、保留可管理且不得被自动复活';
COMMENT ON COLUMN user_memory.use_count IS '全文加载成功次数，用于检索排序的频次加权';
COMMENT ON COLUMN user_memory.last_used_at IS '最近一次全文加载时间；为 null 表示从未被加载过';
COMMENT ON COLUMN user_memory.created_by IS '创建审计操作者（会话操作者或 ADMIN 用户名），无权限语义';
COMMENT ON COLUMN user_memory.updated_by IS '更新审计操作者（会话操作者或 ADMIN 用户名），无权限语义';
