ALTER TABLE user_memory
    ADD COLUMN revision BIGINT NOT NULL DEFAULT 1,
    ADD CONSTRAINT ck_user_memory_revision_positive CHECK (revision >= 1);

CREATE TABLE user_memory_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id BIGINT,
    revision BIGINT NOT NULL,
    snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    operation VARCHAR(32) NOT NULL,
    relation VARCHAR(32),
    reason VARCHAR(600),
    source_run_id BIGINT,
    source_conversation_id BIGINT,
    source_message_id BIGINT,
    operator_id VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_user_memory_revision_number_positive CHECK (revision >= 1),
    CONSTRAINT uq_user_memory_revision_memory_version UNIQUE (memory_id, revision),
    CONSTRAINT fk_user_memory_revision_memory FOREIGN KEY (memory_id)
        REFERENCES user_memory(id) ON DELETE SET NULL
);

CREATE INDEX idx_user_memory_revision_memory
    ON user_memory_revision(memory_id, revision DESC);
CREATE INDEX idx_user_memory_revision_source_run
    ON user_memory_revision(source_run_id);

INSERT INTO user_memory_revision (
    memory_id, revision, snapshot, operation, relation, reason,
    source_run_id, source_conversation_id, operator_id, created_at
)
SELECT id, 1,
       jsonb_build_object(
           'title', title, 'summary', summary, 'content', content,
           'category', category, 'status', status, 'scope', scope_type,
           'projectId', project_id
       ),
       'BASELINE', NULL, '迁移前已有记忆的初始快照',
       source_run_id, source_conversation_id, created_by, created_at
FROM user_memory;
