-- LoreDock 快速迭代阶段数据库最终基线。
-- 不兼容历史开发库；结构变化后必须删除并重建开发数据库，禁止补写兼容迁移或双写。

-- 基础存储与后台任务
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE stored_object (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(16) NOT NULL,
    original_filename VARCHAR(512) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    CONSTRAINT ck_stored_object_status
        CHECK (status IN ('AVAILABLE', 'DELETING')),
    CONSTRAINT ck_stored_object_size
        CHECK (size_bytes >= 0),
    CONSTRAINT ck_stored_object_sha256
        CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_stored_object_audit_time
        CHECK (updated_at >= created_at)
);

COMMENT ON TABLE stored_object IS '本地持久化对象的可读取元数据；文件系统与数据库协调时以该记录为读取事实';
COMMENT ON COLUMN stored_object.object_key IS '服务生成的安全对象键，不接受原始文件名作为路径';
COMMENT ON COLUMN stored_object.status IS 'AVAILABLE 可读取，DELETING 正在执行幂等删除';

CREATE TABLE background_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    progress SMALLINT NOT NULL DEFAULT 0,
    input_object_key VARCHAR(64),
    project_id BIGINT,
    branch_id BIGINT,
    snapshot_id BIGINT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    heartbeat_at TIMESTAMPTZ,
    owner_instance VARCHAR(128),
    error_code VARCHAR(64),
    error_message VARCHAR(1024),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    CONSTRAINT ck_background_job_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_background_job_progress
        CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT ck_background_job_audit_time
        CHECK (updated_at >= created_at),
    CONSTRAINT ck_background_job_lifecycle_time
        CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
);

COMMENT ON TABLE background_job IS 'MVP 单实例后台工作的持久化状态，不承担分布式调度或自动重试';
COMMENT ON COLUMN background_job.status IS '仅允许 PENDING→RUNNING→SUCCEEDED、FAILED 或 CANCELLED';
COMMENT ON COLUMN background_job.error_message IS '经过脱敏和长度限制的诊断摘要，不保存堆栈或输入正文';

CREATE INDEX idx_background_job_status_created
    ON background_job(status, created_at);

CREATE INDEX idx_background_job_running_heartbeat
    ON background_job(heartbeat_at)
    WHERE status = 'RUNNING';

-- 项目与分支
CREATE TABLE project_space (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    technology_stack VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    CONSTRAINT uq_project_space_identifier UNIQUE (identifier),
    CONSTRAINT ck_project_space_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_project_space_audit_time CHECK (updated_at >= created_at)
);

CREATE TABLE project_branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    CONSTRAINT uq_project_branch_project_name UNIQUE (project_id, name),
    CONSTRAINT fk_project_branch_project
        FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT ck_project_branch_audit_time CHECK (updated_at >= created_at)
);

COMMENT ON TABLE project_space IS '知识、代码快照、检索与问答共用的项目范围主数据';
COMMENT ON COLUMN project_space.identifier IS '经领域校验的小写 kebab-case 稳定业务标识';
COMMENT ON COLUMN project_space.status IS 'ENABLED 对普通入口可见，DISABLED 仅管理入口可见且不删除数据';
COMMENT ON TABLE project_branch IS '项目内分支范围；后续隔离使用项目与分支 BIGINT，不使用名称拼接路径';
COMMENT ON COLUMN project_branch.name IS '保留大小写的 Git 风格分支名，不得直接作为文件路径';

CREATE INDEX idx_project_space_status_name
    ON project_space(status, name, id);

CREATE INDEX idx_project_branch_project_name
    ON project_branch(project_id, name, id);

-- 知识文档与导入
CREATE TABLE knowledge_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    format VARCHAR(16) NOT NULL,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    directory_path VARCHAR(1000) NOT NULL,
    tags TEXT NOT NULL DEFAULT '[]',
    scope_type VARCHAR(16) NOT NULL,
    project_id BIGINT,
    branch_id BIGINT,
    source_type VARCHAR(16) NOT NULL,
    wiki_url VARCHAR(2000),
    original_filename VARCHAR(512),
    curation_note VARCHAR(2000),
    status VARCHAR(16) NOT NULL,
    revision BIGINT NOT NULL,
    replaces_document_id BIGINT,
    published_at TIMESTAMPTZ,
    published_by VARCHAR(255),
    archived_at TIMESTAMPTZ,
    archived_by VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    CONSTRAINT fk_knowledge_document_project
        FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT fk_knowledge_document_branch
        FOREIGN KEY (branch_id) REFERENCES project_branch(id),
    CONSTRAINT fk_knowledge_document_replaces
        FOREIGN KEY (replaces_document_id) REFERENCES knowledge_document(id),
    CONSTRAINT uq_knowledge_document_replaces_document UNIQUE (replaces_document_id),
    CONSTRAINT ck_knowledge_document_format
        CHECK (format IN ('MARKDOWN', 'PLAIN_TEXT')),
    CONSTRAINT ck_knowledge_document_content
        CHECK (length(title) > 0 AND length(body) > 0),
    CONSTRAINT ck_knowledge_document_scope
        CHECK (
            (scope_type = 'GLOBAL' AND project_id IS NULL AND branch_id IS NULL)
            OR (scope_type = 'PROJECT' AND project_id IS NOT NULL AND branch_id IS NULL)
            OR (scope_type = 'BRANCH' AND project_id IS NOT NULL AND branch_id IS NOT NULL)
        ),
    CONSTRAINT ck_knowledge_document_source
        CHECK (
            (source_type = 'MANUAL' AND wiki_url IS NULL AND original_filename IS NULL)
            OR (source_type = 'WIKI' AND wiki_url IS NOT NULL)
            OR (source_type = 'UPLOAD' AND wiki_url IS NULL AND original_filename IS NOT NULL)
        ),
    CONSTRAINT ck_knowledge_document_revision CHECK (revision > 0),
    CONSTRAINT ck_knowledge_document_replacement_not_self
        CHECK (replaces_document_id IS NULL OR replaces_document_id <> id),
    CONSTRAINT ck_knowledge_document_lifecycle
        CHECK (
            (status = 'DRAFT'
                AND published_at IS NULL AND published_by IS NULL
                AND archived_at IS NULL AND archived_by IS NULL)
            OR (status = 'PUBLISHED'
                AND published_at IS NOT NULL AND published_by IS NOT NULL
                AND archived_at IS NULL AND archived_by IS NULL)
            OR (status = 'ARCHIVED'
                AND archived_at IS NOT NULL AND archived_by IS NOT NULL
                AND ((published_at IS NULL AND published_by IS NULL)
                    OR (published_at IS NOT NULL AND published_by IS NOT NULL)))
        ),
    CONSTRAINT ck_knowledge_document_audit_time
        CHECK (updated_at >= created_at)
);

COMMENT ON TABLE knowledge_document IS '人工审核知识的当前聚合状态；revision 不代表正文版本历史';
COMMENT ON COLUMN knowledge_document.directory_path IS '知识分类逻辑路径，不得作为文件系统路径';
COMMENT ON COLUMN knowledge_document.replaces_document_id IS '当前文档替代的旧文档；唯一约束保护一个旧文档只有一个当前替代者';

CREATE TABLE knowledge_import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key VARCHAR(64) NOT NULL,
    original_filename VARCHAR(512) NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    project_id BIGINT,
    branch_id BIGINT,
    directory_prefix VARCHAR(1000) NOT NULL,
    status VARCHAR(16) NOT NULL,
    succeeded_count INTEGER NOT NULL,
    failed_count INTEGER NOT NULL,
    ignored_count INTEGER NOT NULL,
    results_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    CONSTRAINT fk_knowledge_import_batch_project
        FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT fk_knowledge_import_batch_branch
        FOREIGN KEY (branch_id) REFERENCES project_branch(id),
    CONSTRAINT ck_knowledge_import_batch_scope
        CHECK (
            (scope_type = 'GLOBAL' AND project_id IS NULL AND branch_id IS NULL)
            OR (scope_type = 'PROJECT' AND project_id IS NOT NULL AND branch_id IS NULL)
            OR (scope_type = 'BRANCH' AND project_id IS NOT NULL AND branch_id IS NOT NULL)
        ),
    CONSTRAINT ck_knowledge_import_batch_status
        CHECK (status IN ('COMPLETED', 'PARTIAL', 'FAILED')),
    CONSTRAINT ck_knowledge_import_batch_counts
        CHECK (succeeded_count >= 0 AND failed_count >= 0 AND ignored_count >= 0),
    CONSTRAINT ck_knowledge_import_batch_audit_time
        CHECK (updated_at >= created_at)
);

CREATE INDEX idx_knowledge_document_admin_list
    ON knowledge_document(status, scope_type, directory_path, updated_at DESC, id ASC);

CREATE INDEX idx_knowledge_document_project_scope
    ON knowledge_document(project_id, branch_id, status, updated_at DESC, id ASC);

CREATE INDEX idx_knowledge_import_batch_created
    ON knowledge_import_batch(created_at DESC, id ASC);

-- 代码快照与代码索引 generation
CREATE TABLE code_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    commit_hash VARCHAR(64) NOT NULL,
    input_object_key VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    previous_snapshot_id BIGINT,
    indexed_file_count BIGINT NOT NULL DEFAULT 0,
    ignored_file_count BIGINT NOT NULL DEFAULT 0,
    indexed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    CONSTRAINT uq_code_snapshot_input_object UNIQUE (input_object_key),
    CONSTRAINT fk_code_snapshot_project
        FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT fk_code_snapshot_branch
        FOREIGN KEY (branch_id) REFERENCES project_branch(id),
    CONSTRAINT fk_code_snapshot_previous
        FOREIGN KEY (previous_snapshot_id) REFERENCES code_snapshot(id),
    CONSTRAINT ck_code_snapshot_commit
        CHECK (commit_hash ~ '^[0-9a-f]{7,64}$'),
    CONSTRAINT ck_code_snapshot_status
        CHECK (status IN ('CANDIDATE', 'ACTIVE', 'RETIRED', 'FAILED')),
    CONSTRAINT ck_code_snapshot_counts
        CHECK (indexed_file_count >= 0 AND ignored_file_count >= 0),
    CONSTRAINT ck_code_snapshot_previous_not_self
        CHECK (previous_snapshot_id IS NULL OR previous_snapshot_id <> id),
    CONSTRAINT ck_code_snapshot_activation
        CHECK ((status IN ('CANDIDATE', 'FAILED') AND indexed_at IS NULL)
            OR (status IN ('ACTIVE', 'RETIRED') AND indexed_at IS NOT NULL)),
    CONSTRAINT ck_code_snapshot_audit_time
        CHECK (updated_at >= created_at)
);

COMMENT ON TABLE code_snapshot IS '指定项目分支和声明 commit 的代码快照业务生命周期；只有 ACTIVE 可进入普通查询';
COMMENT ON COLUMN code_snapshot.input_object_key IS '可重建原始 ZIP 的不透明对象键，普通响应和日志不得返回';
COMMENT ON COLUMN code_snapshot.previous_snapshot_id IS '前一成功活动快照，仅用于 INITIAL/CHANGED/UNCHANGED 提示而非完整 diff';

CREATE UNIQUE INDEX uq_code_snapshot_branch_active
    ON code_snapshot(branch_id)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_code_snapshot_admin_list
    ON code_snapshot(project_id, branch_id, created_at DESC, id ASC);

ALTER TABLE background_job
    ADD CONSTRAINT fk_background_job_project
        FOREIGN KEY (project_id) REFERENCES project_space(id),
    ADD CONSTRAINT fk_background_job_branch
        FOREIGN KEY (branch_id) REFERENCES project_branch(id),
    ADD CONSTRAINT fk_background_job_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES code_snapshot(id);

-- 构建与重建共享这一数据库排他入口，避免重启或意外多实例让同分支任务竞速激活。
CREATE UNIQUE INDEX uq_background_job_code_branch_active
    ON background_job(branch_id)
    WHERE job_type IN ('CODE_SNAPSHOT_BUILD', 'CODE_SNAPSHOT_REINDEX')
      AND status IN ('PENDING', 'RUNNING');

CREATE TABLE code_index_generation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    document_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    activated_at TIMESTAMPTZ,
    CONSTRAINT uq_code_index_generation_job UNIQUE (job_id),
    CONSTRAINT fk_code_index_generation_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES code_snapshot(id),
    CONSTRAINT fk_code_index_generation_job
        FOREIGN KEY (job_id) REFERENCES background_job(id),
    CONSTRAINT ck_code_index_generation_status
        CHECK (status IN ('BUILDING', 'ACTIVE', 'RETIRED', 'FAILED')),
    CONSTRAINT ck_code_index_generation_count
        CHECK (document_count >= 0),
    CONSTRAINT ck_code_index_generation_activation
        CHECK ((status IN ('BUILDING', 'FAILED') AND activated_at IS NULL)
            OR (status IN ('ACTIVE', 'RETIRED') AND activated_at IS NOT NULL))
);

COMMENT ON TABLE code_index_generation IS '一次代码索引任务生成的独立 Lucene generation；数据库只激活已发布且验证可读的目录';
COMMENT ON COLUMN code_index_generation.id IS '同时作为服务端生成的物理目录名，任何客户端都不能指定';

CREATE UNIQUE INDEX uq_code_index_generation_snapshot_active
    ON code_index_generation(snapshot_id)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_code_index_generation_snapshot_created
    ON code_index_generation(snapshot_id, created_at DESC, id ASC);

-- 知识检索 generation 与分块
-- 测试和多 schema 部署中 vector 扩展可能安装在另一命名空间；只在本事务补充其 schema，建表仍落在当前 schema。
SELECT set_config(
    'search_path',
    quote_ident(current_schema()) || ',' || quote_ident(namespace.nspname),
    true
)
FROM pg_extension extension
JOIN pg_namespace namespace ON namespace.oid = extension.extnamespace
WHERE extension.extname = 'vector';

CREATE TABLE knowledge_index_generation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    model_id VARCHAR(200) NOT NULL,
    model_checksum CHAR(64) NOT NULL,
    vector_dimension INTEGER NOT NULL,
    chunk_strategy_version VARCHAR(64) NOT NULL,
    fusion_config_version VARCHAR(64) NOT NULL,
    document_count BIGINT NOT NULL,
    chunk_count BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    activated_at TIMESTAMPTZ,
    CONSTRAINT uq_knowledge_index_generation_job UNIQUE (job_id),
    CONSTRAINT fk_knowledge_index_generation_job
        FOREIGN KEY (job_id) REFERENCES background_job(id),
    CONSTRAINT ck_knowledge_index_generation_status
        CHECK (status IN ('BUILDING', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_knowledge_index_generation_model
        CHECK (length(model_id) > 0 AND model_checksum ~ '^[0-9A-Fa-f]{64}$'),
    CONSTRAINT ck_knowledge_index_generation_dimension CHECK (vector_dimension = 512),
    CONSTRAINT ck_knowledge_index_generation_versions
        CHECK (length(chunk_strategy_version) > 0 AND length(fusion_config_version) > 0),
    CONSTRAINT ck_knowledge_index_generation_counts
        CHECK (document_count >= 0 AND chunk_count >= 0),
    CONSTRAINT ck_knowledge_index_generation_activation
        CHECK ((status = 'BUILDING' AND activated_at IS NULL)
            OR (status IN ('ACTIVE', 'RETIRED') AND activated_at IS NOT NULL))
);

CREATE UNIQUE INDEX uq_knowledge_index_generation_single_active
    ON knowledge_index_generation ((status)) WHERE status = 'ACTIVE';

COMMENT ON TABLE knowledge_index_generation IS
    '知识索引构建、模型配置、计数与激活状态的唯一 generation 事实';
COMMENT ON COLUMN knowledge_index_generation.model_checksum IS
    '离线 ONNX 模型 SHA-256，用于查询和索引模型一致性校验';

CREATE TABLE knowledge_search_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    chunk_no INTEGER NOT NULL,
    start_offset INTEGER NOT NULL,
    end_offset INTEGER NOT NULL,
    content TEXT NOT NULL,
    source_revision BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    tags JSONB NOT NULL,
    wiki_url VARCHAR(2000),
    original_filename VARCHAR(512),
    curation_note VARCHAR(2000),
    title_terms TEXT NOT NULL,
    tag_terms TEXT NOT NULL,
    content_terms TEXT NOT NULL,
    search_vector TSVECTOR NOT NULL,
    embedding VECTOR(512) NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    project_id BIGINT,
    branch_id BIGINT,
    format VARCHAR(16) NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    normalized_tags TEXT[] NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_knowledge_search_chunk UNIQUE (generation_id, document_id, chunk_no),
    CONSTRAINT fk_knowledge_search_chunk_generation
        FOREIGN KEY (generation_id) REFERENCES knowledge_index_generation(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_search_chunk_document
        FOREIGN KEY (document_id) REFERENCES knowledge_document(id),
    CONSTRAINT fk_knowledge_search_chunk_project
        FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT fk_knowledge_search_chunk_branch
        FOREIGN KEY (branch_id) REFERENCES project_branch(id),
    CONSTRAINT ck_knowledge_search_chunk_number CHECK (chunk_no >= 0),
    CONSTRAINT ck_knowledge_search_chunk_offsets
        CHECK (start_offset >= 0 AND end_offset > start_offset),
    CONSTRAINT ck_knowledge_search_chunk_revision CHECK (source_revision > 0),
    CONSTRAINT ck_knowledge_search_chunk_content CHECK (length(content) > 0),
    CONSTRAINT ck_knowledge_search_chunk_scope
        CHECK (
            (scope_type = 'GLOBAL' AND project_id IS NULL AND branch_id IS NULL)
            OR (scope_type = 'PROJECT' AND project_id IS NOT NULL AND branch_id IS NULL)
            OR (scope_type = 'BRANCH' AND project_id IS NOT NULL AND branch_id IS NOT NULL)
        ),
    CONSTRAINT ck_knowledge_search_chunk_format CHECK (format IN ('MARKDOWN', 'PLAIN_TEXT')),
    CONSTRAINT ck_knowledge_search_chunk_source CHECK (source_type IN ('MANUAL', 'WIKI', 'UPLOAD')),
    CONSTRAINT ck_knowledge_search_chunk_tags CHECK (array_position(normalized_tags, NULL) IS NULL)
);

COMMENT ON TABLE knowledge_search_chunk IS
    '固定 generation 的可追溯知识分块；冗余范围字段使隔离条件在候选 SQL 阶段生效';
COMMENT ON COLUMN knowledge_search_chunk.start_offset IS '相对投影正文的 Unicode code point 起始偏移';
COMMENT ON COLUMN knowledge_search_chunk.end_offset IS '相对投影正文的 Unicode code point 结束偏移（不含）';

CREATE INDEX idx_knowledge_search_chunk_scope
    ON knowledge_search_chunk(
        generation_id, scope_type, project_id, branch_id, format, source_type, document_id, chunk_no
    );

CREATE INDEX idx_knowledge_search_chunk_fulltext
    ON knowledge_search_chunk USING GIN(search_vector);

CREATE INDEX idx_knowledge_search_chunk_tags
    ON knowledge_search_chunk USING GIN(normalized_tags);

-- Agent 运行事实
CREATE TABLE agent_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    question_hash CHAR(64) NOT NULL,
    question_length INTEGER NOT NULL,
    project_id BIGINT NOT NULL,
    project_identifier VARCHAR(64) NOT NULL,
    branch_id BIGINT NOT NULL,
    branch_name VARCHAR(255) NOT NULL,
    snapshot_id BIGINT,
    commit_hash VARCHAR(64),
    knowledge_generation_id BIGINT,
    agent_name VARCHAR(64) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    config_summary VARCHAR(256) NOT NULL,
    status VARCHAR(16) NOT NULL,
    answer_basis VARCHAR(32),
    result_type VARCHAR(16),
    result_text VARCHAR(12000),
    refusal_reason VARCHAR(64),
    error_code VARCHAR(64),
    event_sequence BIGINT NOT NULL DEFAULT 0,
    step_count INTEGER NOT NULL DEFAULT 0,
    model_call_count INTEGER NOT NULL DEFAULT 0,
    retrieval_count INTEGER NOT NULL DEFAULT 0,
    trimmed_character_count INTEGER NOT NULL DEFAULT 0,
    input_tokens BIGINT,
    output_tokens BIGINT,
    elapsed_millis BIGINT,
    accepted_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_agent_run_operator_idempotency UNIQUE (operator_id, idempotency_key),
    CONSTRAINT fk_agent_run_project FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT fk_agent_run_branch FOREIGN KEY (branch_id) REFERENCES project_branch(id),
    CONSTRAINT fk_agent_run_snapshot FOREIGN KEY (snapshot_id) REFERENCES code_snapshot(id),
    CONSTRAINT fk_agent_run_knowledge_generation
        FOREIGN KEY (knowledge_generation_id) REFERENCES knowledge_index_generation(id),
    CONSTRAINT ck_agent_run_operator CHECK (length(operator_id) BETWEEN 1 AND 128),
    CONSTRAINT ck_agent_run_idempotency CHECK (length(idempotency_key) BETWEEN 1 AND 128),
    CONSTRAINT ck_agent_run_hashes CHECK (
        request_hash ~ '^[0-9a-f]{64}$' AND question_hash ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_agent_run_task CHECK (task_type = 'project_qa'),
    CONSTRAINT ck_agent_run_question_length CHECK (question_length BETWEEN 1 AND 2000),
    CONSTRAINT ck_agent_run_scope_text CHECK (
        length(project_identifier) BETWEEN 1 AND 64 AND length(branch_name) BETWEEN 1 AND 255
    ),
    CONSTRAINT ck_agent_run_snapshot_pair CHECK (
        (snapshot_id IS NULL AND commit_hash IS NULL)
        OR (snapshot_id IS NOT NULL AND commit_hash ~ '^[0-9a-f]{7,64}$')
    ),
    CONSTRAINT ck_agent_run_model CHECK (
        length(agent_name) > 0 AND length(model_name) > 0 AND length(config_summary) > 0
    ),
    CONSTRAINT ck_agent_run_counts CHECK (
        event_sequence >= 0 AND step_count >= 0 AND model_call_count >= 0 AND retrieval_count >= 0
        AND trimmed_character_count >= 0
        AND (input_tokens IS NULL OR input_tokens >= 0)
        AND (output_tokens IS NULL OR output_tokens >= 0)
        AND (elapsed_millis IS NULL OR elapsed_millis >= 0)
    ),
    CONSTRAINT ck_agent_run_status CHECK (status IN ('ACCEPTED', 'RUNNING', 'COMPLETED', 'FAILED', 'TERMINATED')),
    CONSTRAINT ck_agent_run_answer_basis CHECK (answer_basis IS NULL OR answer_basis IN (
        'BUSINESS_RULE', 'CURRENT_IMPLEMENTATION', 'MIXED'
    )),
    CONSTRAINT ck_agent_run_result_type CHECK (result_type IS NULL OR result_type IN ('ANSWER', 'REFUSAL')),
    CONSTRAINT ck_agent_run_lifecycle CHECK (
        (status = 'ACCEPTED'
            AND started_at IS NULL AND finished_at IS NULL
            AND result_type IS NULL AND result_text IS NULL AND refusal_reason IS NULL AND error_code IS NULL)
        OR (status = 'RUNNING'
            AND started_at IS NOT NULL AND finished_at IS NULL
            AND result_type IS NULL AND result_text IS NULL AND refusal_reason IS NULL AND error_code IS NULL)
        OR (status = 'COMPLETED'
            AND started_at IS NOT NULL AND finished_at IS NOT NULL AND error_code IS NULL
            AND result_type IS NOT NULL AND result_text IS NOT NULL AND length(result_text) > 0
            AND ((result_type = 'ANSWER' AND refusal_reason IS NULL)
                OR (result_type = 'REFUSAL' AND refusal_reason IS NOT NULL)))
        OR (status IN ('FAILED', 'TERMINATED')
            AND finished_at IS NOT NULL AND error_code IS NOT NULL
            AND result_type IS NULL AND result_text IS NULL AND refusal_reason IS NULL)
    ),
    CONSTRAINT ck_agent_run_time CHECK (
        updated_at >= accepted_at
        AND (started_at IS NULL OR started_at >= accepted_at)
        AND (finished_at IS NULL OR finished_at >= accepted_at)
    )
);

COMMENT ON TABLE agent_run IS '运行状态、Agent/模型摘要与范围的持久化事实；完整问题只保存 SHA-256 和 Unicode 长度';
COMMENT ON COLUMN agent_run.question_hash IS '用于幂等比较的完整问题摘要，不保存问题原文';
COMMENT ON COLUMN agent_run.input_tokens IS '模型未提供 usage 时保持 NULL，不能伪造为零';

CREATE INDEX idx_agent_run_project_accepted ON agent_run(project_id, accepted_at DESC, id);
CREATE INDEX idx_agent_run_non_terminal ON agent_run(status, accepted_at) WHERE status IN ('ACCEPTED', 'RUNNING');

CREATE TABLE agent_run_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    sequence BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_agent_run_event_sequence UNIQUE (run_id, sequence),
    CONSTRAINT fk_agent_run_event_run FOREIGN KEY (run_id) REFERENCES agent_run(id) ON DELETE CASCADE,
    CONSTRAINT ck_agent_run_event_sequence CHECK (sequence > 0),
    CONSTRAINT ck_agent_run_event_type CHECK (event_type IN (
        'RUN_ACCEPTED', 'RUN_STARTED', 'MODEL_STARTED', 'SOURCE_FOUND',
        'RUN_COMPLETED', 'RUN_FAILED', 'RUN_TERMINATED'
    )),
    CONSTRAINT ck_agent_run_event_payload_size CHECK (octet_length(payload::text) <= 16384)
);

COMMENT ON TABLE agent_run_event IS '先提交到数据库再供下游按序读取的公开事件；禁止隐藏思维链和完整证据正文';
CREATE INDEX idx_agent_run_event_after_sequence ON agent_run_event(run_id, sequence);

CREATE TABLE agent_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    evidence_key VARCHAR(32) NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    retained BOOLEAN NOT NULL,
    cited BOOLEAN NOT NULL DEFAULT FALSE,
    citation_order INTEGER,
    relevance DOUBLE PRECISION NOT NULL,
    document_id BIGINT,
    snapshot_id BIGINT,
    project_identifier VARCHAR(64) NOT NULL,
    branch_name VARCHAR(255) NOT NULL,
    commit_hash VARCHAR(64),
    repository_path VARCHAR(1000),
    title VARCHAR(200),
    source_updated_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_agent_evidence_key UNIQUE (run_id, evidence_key),
    CONSTRAINT uq_agent_evidence_run_id UNIQUE (run_id, id),
    CONSTRAINT fk_agent_evidence_run FOREIGN KEY (run_id) REFERENCES agent_run(id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_evidence_document FOREIGN KEY (document_id) REFERENCES knowledge_document(id),
    CONSTRAINT fk_agent_evidence_snapshot FOREIGN KEY (snapshot_id) REFERENCES code_snapshot(id),
    CONSTRAINT ck_agent_evidence_key CHECK (evidence_key ~ '^E[1-9][0-9]{0,8}$'),
    CONSTRAINT ck_agent_evidence_type CHECK (source_type IN ('KNOWLEDGE', 'CODE')),
    CONSTRAINT ck_agent_evidence_relevance CHECK (relevance >= 0.0 AND relevance <= 1.0),
    CONSTRAINT ck_agent_evidence_citation CHECK (
        (cited AND retained AND citation_order > 0)
        OR (NOT cited AND citation_order IS NULL)
    ),
    CONSTRAINT ck_agent_evidence_scope_text CHECK (
        length(project_identifier) BETWEEN 1 AND 64 AND length(branch_name) BETWEEN 1 AND 255
    ),
    CONSTRAINT ck_agent_evidence_source CHECK (
        (source_type = 'KNOWLEDGE'
            AND document_id IS NOT NULL AND snapshot_id IS NULL
            AND commit_hash IS NULL AND repository_path IS NULL
            AND title IS NOT NULL AND length(title) > 0)
        OR (source_type = 'CODE'
            AND document_id IS NULL AND snapshot_id IS NOT NULL
            AND commit_hash ~ '^[0-9a-f]{7,64}$'
            AND repository_path IS NOT NULL AND length(repository_path) BETWEEN 1 AND 1000)
    ),
    CONSTRAINT ck_agent_evidence_metadata_size CHECK (octet_length(metadata::text) <= 16384)
);

COMMENT ON TABLE agent_evidence IS '运行内有限证据台账，只保存引用来源和摘要元数据，正文仅存在于有界模型上下文';
COMMENT ON COLUMN agent_evidence.repository_path IS '仓库相对路径，禁止服务器绝对路径';
CREATE INDEX idx_agent_evidence_run ON agent_evidence(run_id, evidence_key);
CREATE UNIQUE INDEX uq_agent_evidence_citation_order
    ON agent_evidence(run_id, citation_order) WHERE cited;

-- Spring AI Alibaba Graph checkpoint；框架 UUID 只作为唯一协议键，数据库主键仍统一使用 identity BIGINT。
CREATE TABLE graphthread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id UUID NOT NULL UNIQUE,
    thread_name VARCHAR(255),
    is_released BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX idx_unique_lg4jthread_thread_name_unreleased
    ON graphthread(thread_name) WHERE is_released = FALSE;

CREATE TABLE graphcheckpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkpoint_id UUID NOT NULL UNIQUE,
    parent_checkpoint_id UUID,
    thread_id UUID NOT NULL,
    node_id VARCHAR(255),
    next_node_id VARCHAR(255),
    state_data JSONB NOT NULL,
    state_content_type VARCHAR(100) NOT NULL,
    saved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_graphcheckpoint_thread
        FOREIGN KEY (thread_id) REFERENCES graphthread(thread_id) ON DELETE CASCADE
);

CREATE INDEX idx_lg4jcheckpoint_thread_id ON graphcheckpoint(thread_id);
CREATE INDEX idx_lg4jcheckpoint_thread_id_saved_at_desc
    ON graphcheckpoint(thread_id, saved_at DESC);

-- Web 问答与知识缺口反馈
CREATE TABLE web_qa_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    project_identifier VARCHAR(64) NOT NULL,
    branch_id BIGINT NOT NULL,
    branch_name VARCHAR(255) NOT NULL,
    run_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_web_qa_question_operator_key UNIQUE (operator_id, idempotency_key),
    CONSTRAINT uq_web_qa_question_run UNIQUE (run_id),
    CONSTRAINT uq_web_qa_question_run_id UNIQUE (run_id, id),
    CONSTRAINT fk_web_qa_question_project FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT fk_web_qa_question_branch FOREIGN KEY (branch_id) REFERENCES project_branch(id),
    CONSTRAINT fk_web_qa_question_run FOREIGN KEY (run_id) REFERENCES agent_run(id),
    CONSTRAINT ck_web_qa_question_operator CHECK (length(operator_id) BETWEEN 1 AND 128),
    CONSTRAINT ck_web_qa_question_key CHECK (length(idempotency_key) BETWEEN 1 AND 128),
    CONSTRAINT ck_web_qa_question_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_web_qa_question_scope CHECK (
        length(project_identifier) BETWEEN 1 AND 64
        AND length(branch_name) BETWEEN 1 AND 255
    )
);

COMMENT ON TABLE web_qa_question IS '操作者提交的一次项目问答身份与固定范围；问题正文保存在唯一 USER 消息';
CREATE INDEX idx_web_qa_question_history
    ON web_qa_question(operator_id, project_id, created_at DESC, id DESC);

CREATE TABLE web_qa_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    result_type VARCHAR(16),
    refusal_reason VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_web_qa_message_role UNIQUE (question_id, role),
    CONSTRAINT fk_web_qa_message_question
        FOREIGN KEY (question_id) REFERENCES web_qa_question(id) ON DELETE CASCADE,
    CONSTRAINT ck_web_qa_message_role CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT ck_web_qa_message_content CHECK (
        length(content) > 0 AND octet_length(content) <= 48000
    ),
    CONSTRAINT ck_web_qa_message_result CHECK (
        (role = 'USER' AND result_type IS NULL AND refusal_reason IS NULL)
        OR (role = 'ASSISTANT' AND result_type = 'ANSWER' AND refusal_reason IS NULL)
        OR (role = 'ASSISTANT' AND result_type = 'REFUSAL' AND refusal_reason IS NOT NULL)
    )
);

COMMENT ON TABLE web_qa_message IS '单次问答的用户原问题与可恢复终态公开消息；不保存阶段输出或思维链';
CREATE INDEX idx_web_qa_message_question_created
    ON web_qa_message(question_id, created_at, id);

CREATE TABLE knowledge_gap_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    project_identifier VARCHAR(64) NOT NULL,
    branch_id BIGINT NOT NULL,
    branch_name VARCHAR(255) NOT NULL,
    question_id BIGINT,
    run_id BIGINT,
    gap_type VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    question_text TEXT NOT NULL,
    note TEXT,
    result_type VARCHAR(16),
    refusal_reason VARCHAR(64),
    error_code VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    CONSTRAINT uq_knowledge_gap_operator_key UNIQUE (operator_id, idempotency_key),
    CONSTRAINT uq_knowledge_gap_run_id UNIQUE (run_id, id),
    CONSTRAINT fk_knowledge_gap_project FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT fk_knowledge_gap_branch FOREIGN KEY (branch_id) REFERENCES project_branch(id),
    CONSTRAINT fk_knowledge_gap_question_run
        FOREIGN KEY (run_id, question_id) REFERENCES web_qa_question(run_id, id),
    CONSTRAINT ck_knowledge_gap_operator CHECK (
        length(operator_id) BETWEEN 1 AND 128
        AND length(created_by) BETWEEN 1 AND 128
        AND length(updated_by) BETWEEN 1 AND 128
    ),
    CONSTRAINT ck_knowledge_gap_key CHECK (length(idempotency_key) BETWEEN 1 AND 128),
    CONSTRAINT ck_knowledge_gap_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_knowledge_gap_scope CHECK (
        length(project_identifier) BETWEEN 1 AND 64
        AND length(branch_name) BETWEEN 1 AND 255
    ),
    CONSTRAINT ck_knowledge_gap_relation CHECK (
        (question_id IS NULL AND run_id IS NULL)
        OR (question_id IS NOT NULL AND run_id IS NOT NULL)
    ),
    CONSTRAINT ck_knowledge_gap_type CHECK (gap_type IN (
        'NO_ANSWER', 'WRONG_ANSWER', 'OUTDATED_KNOWLEDGE'
    )),
    CONSTRAINT ck_knowledge_gap_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'CLOSED')),
    CONSTRAINT ck_knowledge_gap_question CHECK (
        length(question_text) > 0 AND octet_length(question_text) <= 8000
    ),
    CONSTRAINT ck_knowledge_gap_note CHECK (note IS NULL OR octet_length(note) <= 8000),
    CONSTRAINT ck_knowledge_gap_result CHECK (
        (result_type IS NULL AND refusal_reason IS NULL)
        OR (result_type = 'ANSWER' AND refusal_reason IS NULL)
        OR (result_type = 'REFUSAL' AND refusal_reason IS NOT NULL)
    ),
    CONSTRAINT ck_knowledge_gap_time CHECK (updated_at >= created_at)
);

COMMENT ON TABLE knowledge_gap_feedback IS '成员提交并由管理员单向处理的知识缺口；不自动修改知识或索引';
CREATE INDEX idx_knowledge_gap_feedback_cursor
    ON knowledge_gap_feedback(created_at DESC, id DESC);
CREATE INDEX idx_knowledge_gap_feedback_filter
    ON knowledge_gap_feedback(project_id, branch_id, status, gap_type, created_at DESC, id DESC);

CREATE TABLE knowledge_gap_feedback_citation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    evidence_id BIGINT NOT NULL,
    citation_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_knowledge_gap_citation_order UNIQUE (feedback_id, citation_order),
    CONSTRAINT uq_knowledge_gap_citation_evidence UNIQUE (feedback_id, evidence_id),
    CONSTRAINT fk_knowledge_gap_citation_feedback
        FOREIGN KEY (run_id, feedback_id)
        REFERENCES knowledge_gap_feedback(run_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_gap_citation_evidence
        FOREIGN KEY (run_id, evidence_id)
        REFERENCES agent_evidence(run_id, id) ON DELETE CASCADE,
    CONSTRAINT ck_knowledge_gap_citation_order CHECK (citation_order > 0)
);

COMMENT ON TABLE knowledge_gap_feedback_citation IS '反馈关联的运行时证据快照；复合外键阻止跨运行拼接来源';
CREATE INDEX idx_knowledge_gap_citation_feedback
    ON knowledge_gap_feedback_citation(feedback_id, citation_order);
