-- T7A：项目问答会话聚合与类型化公开事件信封。

CREATE TABLE web_qa_conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id VARCHAR(128) NOT NULL,
    project_id BIGINT NOT NULL,
    project_identifier VARCHAR(64) NOT NULL,
    title VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    last_question_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_web_qa_conversation_project
        FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT ck_web_qa_conversation_operator CHECK (length(operator_id) BETWEEN 1 AND 128),
    CONSTRAINT ck_web_qa_conversation_project CHECK (length(project_identifier) BETWEEN 1 AND 64),
    CONSTRAINT ck_web_qa_conversation_title CHECK (length(title) BETWEEN 1 AND 200),
    CONSTRAINT ck_web_qa_conversation_time CHECK (
        updated_at >= created_at AND last_question_at >= created_at
    )
);

COMMENT ON TABLE web_qa_conversation IS '同一操作者与项目内的问答轮次聚合；不保存模型隐藏消息或证据正文';
CREATE INDEX idx_web_qa_conversation_history
    ON web_qa_conversation(operator_id, project_id, last_question_at DESC, id DESC);

-- 既有 T7 问题稳定映射为一题一会话；沿用 questionId 可避免生成不确定的升级关联。
INSERT INTO web_qa_conversation(
    id, operator_id, project_id, project_identifier, title, created_at, updated_at, last_question_at
)
SELECT q.id,
       q.operator_id,
       q.project_id,
       q.project_identifier,
       substring(m.content from 1 for 200),
       q.created_at,
       q.created_at,
       q.created_at
FROM web_qa_question q
JOIN web_qa_message m ON m.question_id = q.id AND m.role = 'USER';

ALTER TABLE web_qa_question ADD COLUMN conversation_id BIGINT;
UPDATE web_qa_question SET conversation_id = id;
ALTER TABLE web_qa_question ALTER COLUMN conversation_id SET NOT NULL;
ALTER TABLE web_qa_question ADD CONSTRAINT fk_web_qa_question_conversation
    FOREIGN KEY (conversation_id) REFERENCES web_qa_conversation(id);
CREATE INDEX idx_web_qa_question_conversation_created
    ON web_qa_question(conversation_id, created_at, id);

-- 显式推进 identity，保证升级后创建的新会话不会与回填 ID 冲突。
SELECT setval(
    pg_get_serial_sequence('web_qa_conversation', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM web_qa_conversation), 0), 1),
    true
);

ALTER TABLE agent_run_event DROP CONSTRAINT ck_agent_run_event_type;
ALTER TABLE agent_run_event ADD COLUMN subject_type VARCHAR(16);
UPDATE agent_run_event
SET subject_type = CASE
    WHEN event_type = 'MODEL_STARTED' THEN 'MODEL'
    WHEN event_type = 'SOURCE_FOUND' THEN 'TOOL'
    ELSE 'AGENT'
END;
ALTER TABLE agent_run_event ALTER COLUMN subject_type SET NOT NULL;
ALTER TABLE agent_run_event ADD CONSTRAINT ck_agent_run_event_subject
    CHECK (subject_type IN ('AGENT', 'MODEL', 'TOOL', 'VALIDATOR'));
ALTER TABLE agent_run_event ADD CONSTRAINT ck_agent_run_event_type CHECK (event_type IN (
    'RUN_ACCEPTED', 'RUN_STARTED', 'MODEL_STARTED', 'SOURCE_FOUND',
    'AGENT_STAGE', 'MODEL_STAGE', 'TOOL_STARTED', 'TOOL_COMPLETED',
    'SOURCE_DISCOVERED', 'CITATION_VALIDATION', 'PUBLIC_DECISION_SUMMARY', 'ANSWER_DELTA',
    'RUN_COMPLETED', 'RUN_FAILED', 'RUN_TERMINATED'
));

COMMENT ON COLUMN agent_run_event.subject_type IS '公开执行事实主体；不表示模型自述或新的授权边界';
