-- T6B 对话式知识整理：业务会话/消息与既有 Agent run、Graph Checkpoint 分离。

CREATE TABLE knowledge_task_conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    project_identifier VARCHAR(64) NOT NULL,
    trigger_type VARCHAR(16) NOT NULL,
    trigger_reason VARCHAR(1000) NOT NULL,
    target_skill VARCHAR(64) NOT NULL,
    goal VARCHAR(2000) NOT NULL,
    current_draft_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_knowledge_task_operator_idempotency UNIQUE (operator_id, idempotency_key),
    CONSTRAINT fk_knowledge_task_project FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT ck_knowledge_task_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_knowledge_task_trigger CHECK (trigger_type IN ('MANUAL', 'SYSTEM')),
    CONSTRAINT ck_knowledge_task_text CHECK (
        length(operator_id) BETWEEN 1 AND 128
        AND length(idempotency_key) BETWEEN 1 AND 128
        AND length(project_identifier) BETWEEN 1 AND 64
        AND length(trigger_reason) BETWEEN 1 AND 1000
        AND length(target_skill) BETWEEN 1 AND 64
        AND length(goal) BETWEEN 1 AND 2000
    ),
    CONSTRAINT ck_knowledge_task_time CHECK (updated_at >= created_at)
);

CREATE INDEX idx_knowledge_task_project_updated
    ON knowledge_task_conversation(project_id, updated_at DESC, id DESC);

CREATE TABLE knowledge_task_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    run_id BIGINT,
    role VARCHAR(32) NOT NULL,
    subject_name VARCHAR(128),
    content VARCHAR(12000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_knowledge_task_message_conversation
        FOREIGN KEY (conversation_id) REFERENCES knowledge_task_conversation(id) ON DELETE CASCADE,
    CONSTRAINT ck_knowledge_task_message_role CHECK (
        role IN ('SYSTEM_TRIGGER', 'USER', 'COORDINATOR_AGENT', 'SUB_AGENT', 'TOOL')
    ),
    CONSTRAINT ck_knowledge_task_message_content CHECK (length(content) BETWEEN 1 AND 12000)
);

ALTER TABLE agent_run
    ADD COLUMN knowledge_task_conversation_id BIGINT,
    ADD COLUMN thread_id VARCHAR(128),
    ADD COLUMN checkpoint_saved_at TIMESTAMPTZ,
    ADD COLUMN skill_digest CHAR(64),
    ADD COLUMN agent_spec_digest CHAR(64),
    ADD COLUMN tool_names VARCHAR(1000),
    ADD COLUMN tool_call_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE agent_run
    ADD CONSTRAINT fk_agent_run_knowledge_task_conversation
        FOREIGN KEY (knowledge_task_conversation_id) REFERENCES knowledge_task_conversation(id),
    ADD CONSTRAINT uq_agent_run_thread UNIQUE (thread_id),
    ADD CONSTRAINT ck_agent_run_thread_pair CHECK (
        (knowledge_task_conversation_id IS NULL AND thread_id IS NULL)
        OR (knowledge_task_conversation_id IS NOT NULL AND length(thread_id) BETWEEN 1 AND 128)
    ),
    ADD CONSTRAINT ck_agent_run_tool_call_count CHECK (tool_call_count >= 0);

ALTER TABLE agent_run ADD CONSTRAINT ck_agent_run_knowledge_definition CHECK (
    (knowledge_task_conversation_id IS NULL
        AND skill_digest IS NULL AND agent_spec_digest IS NULL AND tool_names IS NULL)
    OR (knowledge_task_conversation_id IS NOT NULL
        AND skill_digest ~ '^[0-9a-f]{64}$'
        AND agent_spec_digest ~ '^[0-9a-f]{64}$'
        AND length(tool_names) BETWEEN 1 AND 1000)
);

ALTER TABLE knowledge_task_message
    ADD CONSTRAINT fk_knowledge_task_message_run FOREIGN KEY (run_id) REFERENCES agent_run(id);

ALTER TABLE agent_run DROP CONSTRAINT ck_agent_run_task;
ALTER TABLE agent_run ADD CONSTRAINT ck_agent_run_task
    CHECK (task_type IN ('project_qa', 'knowledge_curation'));

ALTER TABLE agent_run DROP CONSTRAINT ck_agent_run_status;
ALTER TABLE agent_run ADD CONSTRAINT ck_agent_run_status CHECK (status IN (
    'ACCEPTED', 'RUNNING', 'PAUSE_REQUESTED', 'WAITING_FOR_USER',
    'COMPLETED', 'FAILED', 'TERMINATED', 'CANCELLED'
));

ALTER TABLE agent_run DROP CONSTRAINT ck_agent_run_lifecycle;
ALTER TABLE agent_run ADD CONSTRAINT ck_agent_run_lifecycle CHECK (
    (task_type = 'project_qa' AND (
        (status = 'ACCEPTED'
            AND started_at IS NULL AND finished_at IS NULL
            AND result_type IS NULL AND result_text IS NULL AND refusal_reason IS NULL AND error_code IS NULL)
        OR (status = 'RUNNING'
            AND started_at IS NOT NULL AND finished_at IS NULL
            AND result_type IS NULL AND result_text IS NULL AND refusal_reason IS NULL AND error_code IS NULL)
        OR (status = 'COMPLETED'
            AND started_at IS NOT NULL AND finished_at IS NOT NULL AND error_code IS NULL
            AND result_type IS NOT NULL AND result_text IS NOT NULL AND length(result_text) > 0
            AND ((result_type = 'ANSWER' AND refusal_reason IS NULL)
                OR (result_type = 'REFUSAL' AND refusal_reason IS NOT NULL)))
        OR (status IN ('FAILED', 'TERMINATED')
            AND finished_at IS NOT NULL AND error_code IS NOT NULL
            AND result_type IS NULL AND result_text IS NULL AND refusal_reason IS NULL)
    ))
    OR (task_type = 'knowledge_curation'
        AND result_type IS NULL AND refusal_reason IS NULL
        AND ((status IN ('ACCEPTED', 'RUNNING', 'PAUSE_REQUESTED', 'WAITING_FOR_USER') AND finished_at IS NULL)
            OR (status IN ('COMPLETED', 'FAILED', 'TERMINATED', 'CANCELLED') AND finished_at IS NOT NULL)))
);

CREATE INDEX idx_agent_run_knowledge_task
    ON agent_run(knowledge_task_conversation_id, accepted_at, id)
    WHERE knowledge_task_conversation_id IS NOT NULL;

CREATE TABLE knowledge_draft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    operator_id VARCHAR(128) NOT NULL,
    project_id BIGINT NOT NULL,
    project_identifier VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    baseline_document_id BIGINT,
    current_revision BIGINT NOT NULL DEFAULT 0,
    create_run_id BIGINT NOT NULL,
    create_idempotency_key VARCHAR(128) NOT NULL,
    create_request_hash CHAR(64) NOT NULL,
    published_document_id BIGINT,
    published_revision BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_knowledge_draft_create UNIQUE (create_run_id, create_idempotency_key),
    CONSTRAINT fk_knowledge_draft_conversation FOREIGN KEY (conversation_id) REFERENCES knowledge_task_conversation(id),
    CONSTRAINT fk_knowledge_draft_project FOREIGN KEY (project_id) REFERENCES project_space(id),
    CONSTRAINT fk_knowledge_draft_baseline FOREIGN KEY (baseline_document_id) REFERENCES knowledge_document(id),
    CONSTRAINT fk_knowledge_draft_create_run FOREIGN KEY (create_run_id) REFERENCES agent_run(id),
    CONSTRAINT fk_knowledge_draft_published_document FOREIGN KEY (published_document_id) REFERENCES knowledge_document(id),
    CONSTRAINT ck_knowledge_draft_revision CHECK (current_revision >= 0),
    CONSTRAINT ck_knowledge_draft_hash CHECK (create_request_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_knowledge_draft_publication CHECK (
        (published_document_id IS NULL AND published_revision IS NULL)
        OR (published_document_id IS NOT NULL AND published_revision BETWEEN 0 AND current_revision)
    )
);

ALTER TABLE knowledge_task_conversation
    ADD CONSTRAINT fk_knowledge_task_current_draft FOREIGN KEY (current_draft_id) REFERENCES knowledge_draft(id);

CREATE TABLE knowledge_draft_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id BIGINT NOT NULL,
    revision BIGINT NOT NULL,
    markdown TEXT NOT NULL,
    blocks_json JSONB NOT NULL,
    change_summary VARCHAR(1000) NOT NULL,
    created_by_run_id BIGINT,
    idempotency_key VARCHAR(128),
    request_hash CHAR(64),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_knowledge_draft_revision UNIQUE (draft_id, revision),
    CONSTRAINT uq_knowledge_draft_revision_idempotency UNIQUE (draft_id, created_by_run_id, idempotency_key),
    CONSTRAINT fk_knowledge_draft_revision_draft FOREIGN KEY (draft_id) REFERENCES knowledge_draft(id),
    CONSTRAINT fk_knowledge_draft_revision_run FOREIGN KEY (created_by_run_id) REFERENCES agent_run(id),
    CONSTRAINT ck_knowledge_draft_revision_number CHECK (revision >= 0),
    CONSTRAINT ck_knowledge_draft_revision_hash CHECK (
        (idempotency_key IS NULL AND request_hash IS NULL)
        OR (length(idempotency_key) BETWEEN 1 AND 128 AND request_hash ~ '^[0-9a-f]{64}$')
    )
);

CREATE TABLE knowledge_draft_revision_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id BIGINT NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    CONSTRAINT uq_knowledge_draft_revision_source UNIQUE (revision_id, source_type, source_id),
    CONSTRAINT fk_knowledge_draft_revision_source_revision
        FOREIGN KEY (revision_id) REFERENCES knowledge_draft_revision(id) ON DELETE CASCADE,
    CONSTRAINT ck_knowledge_draft_revision_source_type CHECK (source_type IN ('EVIDENCE', 'USER_MESSAGE'))
);

COMMENT ON TABLE knowledge_task_conversation IS '系统或人工触发的长期知识任务会话；可见消息、运行与草稿通过外键追溯';
COMMENT ON COLUMN agent_run.checkpoint_saved_at IS '最近可读取的框架 Checkpoint 提交时间；页面等待状态不得早于该事实';
COMMENT ON TABLE knowledge_draft_revision IS '不可变 Markdown 草稿修订；正文与稳定区块快照由服务端生成';
