-- T8：管理员勾选的知识文档草稿是知识整理会话的固定、不可变输入集合。

CREATE TABLE knowledge_task_selected_draft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    document_revision BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    directory_path VARCHAR(500) NOT NULL,
    markdown TEXT NOT NULL,
    original_filename VARCHAR(500),
    ordinal INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_knowledge_task_selected_document UNIQUE (conversation_id, document_id),
    CONSTRAINT uq_knowledge_task_selected_ordinal UNIQUE (conversation_id, ordinal),
    CONSTRAINT fk_knowledge_task_selected_conversation
        FOREIGN KEY (conversation_id) REFERENCES knowledge_task_conversation(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_task_selected_document
        FOREIGN KEY (document_id) REFERENCES knowledge_document(id),
    CONSTRAINT ck_knowledge_task_selected_revision CHECK (document_revision > 0),
    CONSTRAINT ck_knowledge_task_selected_ordinal CHECK (ordinal BETWEEN 0 AND 19),
    CONSTRAINT ck_knowledge_task_selected_text CHECK (
        length(title) BETWEEN 1 AND 255
        AND length(directory_path) <= 500
        AND length(markdown) <= 500000
    )
);

CREATE INDEX idx_knowledge_task_selected_conversation
    ON knowledge_task_selected_draft(conversation_id, ordinal);

COMMENT ON TABLE knowledge_task_selected_draft IS
    '启动合并整理时由服务端固定的待处理草稿；Agent 只读且不得在运行中增删';

ALTER TABLE knowledge_draft_revision_source DROP CONSTRAINT ck_knowledge_draft_revision_source_type;
ALTER TABLE knowledge_draft_revision_source ADD CONSTRAINT ck_knowledge_draft_revision_source_type
    CHECK (source_type IN ('EVIDENCE', 'USER_MESSAGE', 'SELECTED_DRAFT'));
