-- 对话式多文档知识整理：任务状态、多文档工作区、Tool Invocation 与任务事件。

ALTER TABLE knowledge_task_conversation
    ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PROCESSING',
    ADD COLUMN close_reason VARCHAR(1000),
    ADD COLUMN closed_at TIMESTAMPTZ;

ALTER TABLE knowledge_task_conversation
    ADD CONSTRAINT ck_knowledge_task_status CHECK (
        status IN ('PROCESSING', 'PUBLISHED', 'CLOSED_NO_CHANGE', 'ABANDONED')
    ),
    ADD CONSTRAINT ck_knowledge_task_close CHECK (
        (status = 'PROCESSING' AND closed_at IS NULL)
        OR (status <> 'PROCESSING' AND closed_at IS NOT NULL)
    );

ALTER TABLE knowledge_task_selected_draft
    ADD COLUMN curation_status VARCHAR(16) NOT NULL DEFAULT 'PROCESSING';

ALTER TABLE knowledge_task_selected_draft
    ADD CONSTRAINT ck_knowledge_task_selected_curation CHECK (
        curation_status IN ('PENDING', 'PROCESSING', 'CURATED')
    );

ALTER TABLE knowledge_draft
    ADD COLUMN operation VARCHAR(16),
    ADD COLUMN baseline_revision BIGINT,
    ADD COLUMN directory_path VARCHAR(500) NOT NULL DEFAULT '';

UPDATE knowledge_draft d
SET operation = CASE WHEN d.baseline_document_id IS NULL THEN 'ADD' ELSE 'MODIFY' END,
    baseline_revision = k.revision,
    directory_path = COALESCE(k.directory_path, '')
FROM knowledge_document k
WHERE d.baseline_document_id = k.id;

UPDATE knowledge_draft
SET operation = 'ADD'
WHERE operation IS NULL;

ALTER TABLE knowledge_draft
    ALTER COLUMN operation SET NOT NULL,
    ADD CONSTRAINT ck_knowledge_draft_operation CHECK (operation IN ('ADD', 'MODIFY')),
    ADD CONSTRAINT ck_knowledge_draft_baseline_pair CHECK (
        (operation = 'ADD' AND baseline_document_id IS NULL AND baseline_revision IS NULL)
        OR (operation = 'MODIFY' AND baseline_document_id IS NOT NULL AND baseline_revision IS NOT NULL)
    );

CREATE INDEX idx_knowledge_draft_conversation
    ON knowledge_draft(conversation_id, id);

CREATE TABLE knowledge_tool_invocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    tool_call_id VARCHAR(128) NOT NULL,
    sequence INTEGER NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    purpose VARCHAR(500) NOT NULL,
    arguments_text VARCHAR(12000),
    result_text VARCHAR(12000),
    result_summary VARCHAR(1000),
    error_text VARCHAR(2000),
    status VARCHAR(16) NOT NULL,
    arguments_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    result_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    duration_millis BIGINT,
    CONSTRAINT fk_knowledge_tool_conversation FOREIGN KEY (conversation_id)
        REFERENCES knowledge_task_conversation(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_tool_run FOREIGN KEY (run_id)
        REFERENCES agent_run(id) ON DELETE CASCADE,
    CONSTRAINT uq_knowledge_tool_call UNIQUE (run_id, tool_call_id),
    CONSTRAINT uq_knowledge_tool_sequence UNIQUE (run_id, sequence),
    CONSTRAINT ck_knowledge_tool_status CHECK (status IN ('STARTED', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_knowledge_tool_duration CHECK (duration_millis IS NULL OR duration_millis >= 0)
);

CREATE INDEX idx_knowledge_tool_conversation
    ON knowledge_tool_invocation(conversation_id, run_id, sequence);

CREATE TABLE knowledge_task_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    run_id BIGINT,
    event_type VARCHAR(64) NOT NULL,
    subject_id BIGINT,
    occurred_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_knowledge_task_event_conversation FOREIGN KEY (conversation_id)
        REFERENCES knowledge_task_conversation(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_task_event_run FOREIGN KEY (run_id)
        REFERENCES agent_run(id) ON DELETE CASCADE,
    CONSTRAINT ck_knowledge_task_event_type CHECK (length(event_type) BETWEEN 1 AND 64)
);

CREATE INDEX idx_knowledge_task_event_cursor
    ON knowledge_task_event(conversation_id, id);

CREATE TABLE knowledge_task_publication (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    operator_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    result_json TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    CONSTRAINT fk_knowledge_task_publication_conversation FOREIGN KEY (conversation_id)
        REFERENCES knowledge_task_conversation(id),
    CONSTRAINT uq_knowledge_task_publication_key UNIQUE (conversation_id, idempotency_key),
    CONSTRAINT ck_knowledge_task_publication_hash CHECK (request_hash ~ '^[0-9a-f]{64}$')
);

COMMENT ON TABLE knowledge_tool_invocation IS '按模型 toolCallId 聚合的知识任务公开 Tool 调用；不包含 ToolContext';
COMMENT ON TABLE knowledge_task_event IS '知识任务 REST 快照之后的持久化 SSE 游标事实';

CREATE UNIQUE INDEX uq_knowledge_project_published_title_directory
    ON knowledge_document(project_id, directory_path, lower(title))
    WHERE status = 'PUBLISHED' AND scope_type = 'PROJECT';
