CREATE TABLE agent_run_retrieval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    sequence_no INTEGER NOT NULL,
    query_text TEXT NOT NULL,
    documents JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_agent_run_retrieval_seq UNIQUE (run_id, sequence_no),
    CONSTRAINT fk_agent_run_retrieval_run FOREIGN KEY (run_id) REFERENCES agent_run(id) ON DELETE CASCADE
);

COMMENT ON TABLE agent_run_retrieval IS '每次知识检索实际提供给模型的内容记录，仅用于评估与审计，不进入公开事件流';
CREATE INDEX idx_agent_run_retrieval_run ON agent_run_retrieval(run_id, sequence_no);
