package io.github.loredock.agent.domain;

/** Agent 运行失败或终止的稳定错误码，不保存底层异常原文。 */
public enum AgentErrorCode {
    AGENT_RUN_IDEMPOTENCY_CONFLICT,
    AGENT_SKILL_UNAVAILABLE,
    AGENT_DISABLED,
    AGENT_RUNTIME_BUSY,
    AGENT_MODEL_UNAVAILABLE,
    AGENT_MODEL_RESPONSE_INVALID,
    AGENT_TOOL_NOT_ALLOWED,
    AGENT_TOOL_SCOPE_VIOLATION,
    AGENT_EVIDENCE_VERSION_CHANGED,
    AGENT_STEP_LIMIT_EXCEEDED,
    AGENT_MODEL_CALL_LIMIT_EXCEEDED,
    AGENT_RUN_TIMEOUT,
    AGENT_RUN_INTERRUPTED,
    AGENT_CITATION_INVALID,
    AGENT_INTERNAL_ERROR
}
